### ISSUE TITLE
Missing releases on Docker Hub

### ISSUE THREAD

**Issue by mwgamble** [masahide/docker-cfn-python-lint#1]
The last few releases don't seem to have made their way to Docker Hub.

**Comment by adrianmace** [comment]
Just came here and discovered the same thing.

**Comment by day1118** [comment]
Can you please investigate this @masahide?
Thanks!

**Comment by adrianmace** [comment]
For those who would like to continue using this for their projects, I've forked this repo and am releasing the containers on the GitHub Container Registry. It's available here: [adrianmace/docker-cfn-python-lint](https://github.com/adrianmace/docker-cfn-python-lint/pkgs/container/docker-cfn-python-lint) and is released with semver compatibility.

**Comment by masahide** [comment]
Sorry.
https://www.docker.com/blog/changes-to-docker-hub-autobuilds/
Effective June 18, 2021, auto-renewals have been suspended due to the discontinuation of Autobuilds in the free version.
@day1118 @mwgamble

**Comment by masahide** [comment]
@adrianmace Thank you!
